services:
  minio:
    image: minio/minio:latest
    container_name: minio
    env_file: .env
    restart: always
    command: server --console-address ":9001" /data
    hostname: minio
    volumes:
      - ./data/minio/data:/data
    ports:
      - "9050:9000"
      - "9051:9001"

  dbt:
    build:
      context: .
      dockerfile: ./docker/dbt/Dockerfile
    container_name: dbt
    env_file: .env
    volumes:
      - ./data/duckdb:/data/duckdb
      - ./covid19_dbt:/covid19_dbt

  dagster:
    build:
      context: .
      dockerfile: ./docker/dagster/Dockerfile
    container_name: dagster
    env_file: .env
    restart: always
    volumes:
      - ./dagster_home:/dagster_home
      - ./pipeline:/pipeline
      - ./covid19_dbt:/covid19_dbt
    ports:
      - "3000:3000"
    depends_on:
      minio:
        condition: service_started
      dbt:
        condition: service_started
