services:
  minio:
    image: minio/minio:latest
    container_name: minio
    env_file: .env
    restart: always
    command: server --console-address ":9001" /data
    hostname: minio
    volumes:
      - ./data/minio/data:/data
    ports:
      - "9050:9000"
      - "9051:9001"

  dbt:
    build:
      context: .
      dockerfile: ./docker/dbt/Dockerfile
    container_name: dbt
    env_file: .env
    volumes:
      - ./data/duckdb:/data/duckdb
      - ./data/duckdb/stored_secrets:/home/.duckdb/stored_secrets
      - ./covid19_dbt:/covid19_dbt

  dagster:
    build:
      context: .
      dockerfile: ./docker/dagster/Dockerfile
    container_name: dagster
    env_file: .env
    restart: always
    volumes:
      - ./data/duckdb:/data/duckdb
      - ./dagster_home:/dagster_home
      - ./dagster:/dagster
      - ./covid19_dbt:/covid19_dbt
    ports:
      - "3000:3000"
    depends_on:
      minio:
        condition: service_started
      dbt:
        condition: service_started

#  jupyter:
#    build:
#      context: .
#      dockerfile: ./docker/jupyter/Dockerfile
#    container_name: jupyter
#    env_file: .env
#    volumes:
#      - ./adhoc:/home/jovyan/work
#      - ./data/duckdb:/home/jovyan/.duckdb
#      - ./data/duckdb:/data/duckdb
#    ports:
#      - "8888:8888"
#    depends_on:
#      minio:
#        condition: service_started

  superset:
    build:
      context: .
      dockerfile: ./docker/superset/Dockerfile
      args:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        SUPERSET_ADMIN: $SUPERSET_ADMIN
        SUPERSET_PASSWORD: $SUPERSET_PASSWORD
        SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    container_name: superset
    env_file: .env
    ports:
      - "8088:8088"
    volumes:
      - ./data/duckdb:/app/superset_home/db
      - ./data/duckdb/stored_secrets:/home/superset/.duckdb/stored_secrets
    depends_on:
      - dagster
#    post_start:
#      - command: "superset import-dashboards -p ./dashboard.zip -u ${SUPERSET_ADMIN}"
