SELECT f1.covid_id,
       dd.date_id AS date_key,
       dd.date_value,
       dd.month_key,
       dd.month_name_short AS month,
       dd.quarter_key,
       dd.year_key,
       dl.country,
       dl.state,
       dl.city,
       dl.longitude,
       dl.latitude,
       dl.administrative_area_level,
       dl.population,
       f1.confirmed,
       f1.deaths,
       f1.recovered,
       f1.active,
       f1.incident_rate,
       f1.case_fatality_ratio,
       f2.hosp,
       f2.icu,
       f2.vent,
       f3.school_closing,
       f3.workplace_closing,
       f3.cancel_events,
       f3.gatherings_restrictions,
       f3.transport_closing,
       f3.stay_home_restrictions,
       f3.international_movement_restrictions,
       f3.internal_movement_restrictions,
       f3.information_campaigns,
       f3.testing_policy,
       f3.contact_tracing,
       f3.facial_coverings,
       f3.vaccination_policy,
       f3.elderly_people_protection,
       f4.tests,
       f4.vaccines,
       f4.people_vaccinated,
       f4.people_fully_vaccinated
FROM {{ ref('fact_covid_cases') }} AS f1
JOIN {{ ref('dim_location') }} AS dl ON dl.location_id = f1.location_id
JOIN {{ ref('dim_date') }} AS dd ON dd.date_id = f1.date_id
LEFT JOIN {{ ref('fact_covid_hospitalization') }} AS f2 ON f2.covid_id = f1.covid_id
LEFT JOIN {{ ref('fact_covid_policy_measures') }} AS f3 ON f3.covid_id = f1.covid_id
LEFT JOIN {{ ref('fact_covid_tests') }} AS f4 ON f4.covid_id = f1.covid_id